"""Add is_fixed_cost column to categories

Revision ID: 604a080f0be6
Revises: 474a51ee8c5a
Create Date: 2025-05-28 22:14:15.657115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604a080f0be6'
down_revision = '474a51ee8c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fixed_cost', sa.Boolean(), nullable=True))

    # Update all existing rows to have False value (variable costs)
    op.execute("UPDATE categories SET is_fixed_cost = false WHERE is_fixed_cost IS NULL")

    # Now make the column not nullable
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('is_fixed_cost', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('is_fixed_cost')

    # ### end Alembic commands ###
